### PR TITLE
Fix initial timestamps (alternative)

### LINKED ISSUE #29: Initial timestamp
Hi @goldibex thanks for writing and maintaning this lib, it is awesome. 

I have a small issue that I was wondering if you might be able to help me solve.

I have a validation rule 
```
type InitialTimestamp extends Number {
  validate() { initial(this, now) }
}
// Returns true if the value is intialized to init, or if it retains it's prior value, otherwise.
initial(value, init) { value == (prior(value) == null ? init : prior(value)) }

```
```
type UserProfile {
  email: String
  signupDate: InitialTimestamp
}
```
The data im using for the write test is like so:
```
userProfile =
  email: 'testUser@test123.com'
  splitType: 'auto'
  signupDate: { ".sv": "timestamp" }

expect(uid:userUID).can.write({userProfile}).to.path userProfilePath + "/#{userUID}"
```

When inforcing this inside of targaryen it seems like there is a timing issue because it rejects it. 

```
 be able to write {"email":"testUser@test123.com","splitType":"auto","signupDate":1463817931069} to /user/profiles/2d7fda85-6ef7-495f-a70b-2e05ccda6e9e, but the rules denied the write.
/user/profiles/2d7fda85-6ef7-495f-a70b-2e05ccda6e9e:.write: "auth != null && auth.uid == $uid"
    => true
/user/profiles/2d7fda85-6ef7-495f-a70b-2e05ccda6e9e:.validate: "newData.hasChildren(['email', 'signupDate'])"
    => true
/user/profiles/2d7fda85-6ef7-495f-a70b-2e05ccda6e9e/email:.validate: "newData.isString()"
    => true
/user/profiles/2d7fda85-6ef7-495f-a70b-2e05ccda6e9e/signupDate:.validate: "newData.isNumber() && newData.val() == (data.val() == null ? now : data.val())"
    => false
Validation failed.
Write was denied.
```

If I change the rule to (less than current time on server):

```
initial(value, init) { value <= (prior(value) == null ? init : prior(value)) }
```

It passes. So I can see in the source that targaryen converts ```{ ".sv": "timestamp" }``` to ```Date.now()``` but I cannot find where it enforces that rule and if it is generating another time at a later point and trying to compare them.

Cheers for any help, Jake

Edit:
It must be comparing these two dates
https://github.com/goldibex/targaryen/blob/6f39c7ee95070e6fcbb1008065876a1e399e2b8c/lib/rule-data-snapshot.js#L37

https://github.com/goldibex/targaryen/blob/6f39c7ee95070e6fcbb1008065876a1e399e2b8c/lib/ruleset.js#L175

### PR DESCRIPTION
**Pull request by dinoboff**
The server timestamps of the data (read) or newData (write/patch) snapshot do not necessary match the rulesets “now” timestamp.

The tests are unstable, relying on the snapshot and ruleset state `now` variable being created in the same nanosecond.

This fix attaches the timestamp to the snapshot and uses it to evaluate the ruleset.

API changes (backward compatible):
- `targaryen.setFirebaseData(data[, now])`;
- jasmine matchers gain an optional `now` argument;
- chai `read`, `write` and `patch` methods gain an optional `now` argument;
- `targaryen/lib/rule-data-snapshot.RuleDataSnapshot(data[, now], path)`;
- `targaryen/lib/rule-data-snapshot.RuleDataSnapshot.convert(data[, now])`;
- `targaryen/lib/helpers.makeNewDataSnap(path, data[, now])`;
- `targayen/lib/ruleset.prototype.tryRead(path, root, auth[, now])`;
- `targayen/lib/ruleset.prototype.tryWrite(path, root, newData, auth[, skipWrite[, skipValidate[, skipOnNoValue[, now]]]])`;
- `targayen/lib/ruleset.prototype.tryPatch(path, root, newData, auth[, skipWrite[, skipValidate[, skipOnNoValue[, now]]]])`.

`now` default to the value returned by`Date.now()` if not provided.

Fix #29.

### CODE REVIEW

File: lib/chai.js [hunk 1]
```diff
@@ -17,24 +17,38 @@ var plugin = function chaiTargaryen(chai, utils) {
     utils.flag(this, 'operation', 'read');
   });
 
-  chai.Assertion.addChainableMethod('write', function(data) {
+  chai.Assertion.addChainableMethod('readAt', function(now) {
+
+    utils.flag(this, 'operation', 'read');;
```
Comment (goldibex) [inline lib/chai.js]: extra semicolon

Comment (dinoboff) [inline lib/chai.js]: @goldibex fixed

**Comment by pthrasher** [comment]
This would be awesome to have published to NPM. What needs to happen to fast track this?

**Comment by dinoboff** [comment]
You can try `npm install @dinoboff/targaryen` while waiting for upstream to merge the PR. It includes #41 and #44

**Comment by goldibex** [comment]
Sorry guys. I'll look at this now.

**Comment by goldibex** [comment]
@dinoboff , would you be interested in becoming a maintainer on `@goldibex/targaryen`? You've obviously demonstrated the interest and ability.

**Comment by dinoboff** [comment]
I would be happy to help.

**Comment by dinoboff** [comment]
@pthrasher you can try with [2.3.0 beta 0](https://github.com/goldibex/targaryen/releases/tag/v2.3.0-0) or 2.3.0 when it's release.
